{{- if .Values.knativeDeploy }}
{{- else }}
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}
  labels:
    draft: {{ default "draft-app" .Values.draft }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  replicas: {{ .Values.replicaCount }}  
  strategy:
    type: RollingUpdate
    rollingParams:
      intervalSeconds: {{ .Values.intervalSeconds }}
      maxSurge: {{ .Values.maxSurge }}
      maxUnavailable: {{ .Values.maxUnavailable }}
      timeoutSeconds: {{ .Values.timeoutSeconds }}
      updatePeriodSeconds: {{ .Values.updatePeriodSeconds }}
  template:
    metadata:
      labels:
        draft: {{ default "draft-app" .Values.draft }}
        app: {{ template "fullname" . }}
{{- if .Values.podAnnotations }}
      annotations:
{{ toYaml .Values.podAnnotations | indent 8 }}
{{- end }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
#         env:
#         # - name: REACT_APP_BACKEND_WS_URL
#         #   valueFrom:
#         #     configMapKeyRef:
#         #       name: chat-frontend-values
#         #       key: REACT_APP_BACKEND_WS_URL
#         - name: DB_USER
# {{- range $pkey, $pval := .Values.env }}
#         - name: {{ $pkey }}
#           value: {{ $pval }}
{{- end }}
        ports:
        - containerPort: {{ .Values.service.internalPort }}
        resources:
{{ toYaml .Values.resources | indent 12 }}
      terminationGracePeriodSeconds: {{ .Values.terminationGracePeriodSeconds }}
{{- end }}
